version: '3.8'

services: 
    tg_bot:
        environment:
            - ConnectionStrings__Database=${POSTGRES_CONNECTION_STRING?pass postgres connection string POSTGRES_CONNECTION_STRING}
        deploy:
            resources:
                limits:
                    cpus: '0.80'
                    memory: 150M