version: '3.8'

services: 
    server:
        environment:
            - ConnectionStrings__PostgresDb=${POSTGRES_CONNECTION_STRING?pass postgres connection string POSTGRES_CONNECTION_STRING}
        deploy:
            resources:
                limits:
                    cpus: '0.10'
                    memory: 150M