version: '3.9'

services: 
    server:
        build: deploy
        environment:
            - ConnectionStrings__PostgresDb=${POSTGRES_CONNECTION_STRING?pass postgres connection string POSTGRES_CONNECTION_STRING}