version: '3.8'

services: 
    tg_bot:
        build: deploy
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__Database=User ID=postgres;Password=password;Server=postgres;Port=5432;Database=finance-manage-dev-db;
    postgres:
        image: postgres:13-alpine
        environment:
            - POSTGRES_PASSWORD=password
        ports:
            - 5432:5432
        volumes:
            - ./postgres-data/:/var/lib/postgresql/data
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
